// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfpayigreprfafoyszpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcGF5aWdyZXByZmFmb3lzenB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjM1NTYsImV4cCI6MjA2NDc5OTU1Nn0.BrYmOkjUSdpjIbdrBmJJ38QXpHwF32Xj78uQ5NoB9yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);